document.addEventListener('DOMContentLoaded', () => {
    const airlineData = [
        { code: "UA", name: "United Air Lines Inc." },
        { code: "AA", name: "American Airlines Inc." },
        { code: "US", name: "US Airways Inc." },
        { code: "F9", name: "Frontier Airlines Inc." },
        { code: "B6", name: "JetBlue Airways" },
        { code: "OO", name: "Skywest Airlines Inc." },
        { code: "AS", name: "Alaska Airlines Inc." },
        { code: "NK", name: "Spirit Air Lines" },
        { code: "WN", name: "Southwest Airlines Co." },
        { code: "DL", name: "Delta Air Lines Inc." },
        { code: "EV", name: "Atlantic Southeast Airlines" },
        { code: "HA", name: "Hawaiian Airlines Inc." },
        { code: "MQ", name: "American Eagle Airlines Inc." },
        { code: "VX", name: "Virgin America" }
    ];
        
    const airportData = [
        { code: "ABE", name: "Lehigh Valley International Airport" },
        { code: "ABI", name: "Abilene Regional Airport" },
        { code: "ABQ", name: "Albuquerque International Sunport" },
        { code: "ABR", name: "Aberdeen Regional Airport" },
        { code: "ABY", name: "Southwest Georgia Regional Airport" },
        { code: "ACK", name: "Nantucket Memorial Airport" },
        { code: "ACT", name: "Waco Regional Airport" },
        { code: "ACV", name: "Arcata Airport" },
        { code: "ACY", name: "Atlantic City International Airport" },
        { code: "ADK", name: "Adak Airport" },
        { code: "ADQ", name: "Kodiak Airport" },
        { code: "AEX", name: "Alexandria International Airport" },
        { code: "AGS", name: "Augusta Regional Airport" },
        { code: "AKN", name: "King Salmon Airport" },
        { code: "ALB", name: "Albany International Airport" },
        { code: "ALO", name: "Waterloo Regional Airport" },
        { code: "AMA", name: "Rick Husband Amarillo International" },
        { code: "ANC", name: "Ted Stevens Anchorage International" },
        { code: "APN", name: "Alpena County Regional Airport" },
        { code: "ASE", name: "Aspen-Pitkin County Airport" },
        { code: "ATL", name: "Hartsfield-Jackson Atlanta Intl" },
        { code: "ATW", name: "Appleton International Airport" },
        { code: "AUS", name: "Austin-Bergstrom International" },
        { code: "AVL", name: "Asheville Regional Airport" },
        { code: "AVP", name: "Wilkes-Barre/Scranton Intl" },
        { code: "AZO", name: "Kalamazoo/Battle Creek Intl" },
        { code: "BDL", name: "Bradley International Airport" },
        { code: "BET", name: "Bethel Airport" },
        { code: "BFL", name: "Meadows Field" },
        { code: "BGM", name: "Greater Binghamton Airport" },
        { code: "BGR", name: "Bangor International Airport" },
        { code: "BHM", name: "Birmingham-Shuttlesworth Intl" },
        { code: "BIL", name: "Billings Logan International" },
        { code: "BIS", name: "Bismarck Municipal Airport" },
        { code: "BJI", name: "Bemidji Regional Airport" },
        { code: "BLI", name: "Bellingham International Airport" },
        { code: "BMI", name: "Central Illinois Regional Airport" },
        { code: "BNA", name: "Nashville International Airport" },
        { code: "BOI", name: "Boise Airport" },
        { code: "BOS", name: "Gen. Edward Lawrence Logan Intl" },
        { code: "BPT", name: "Jack Brooks Regional Airport" },
        { code: "BQK", name: "Brunswick Golden Isles Airport" },
        { code: "BQN", name: "Rafael Hernández Airport" },
        { code: "BRD", name: "Brainerd Lakes Regional Airport" },
        { code: "BRO", name: "Brownsville/South Padre Island Intl" },
        { code: "BRW", name: "Wiley Post-Will Rogers Memorial" },
        { code: "BTM", name: "Bert Mooney Airport" },
        { code: "BTR", name: "Baton Rouge Metropolitan Airport" },
        { code: "BTV", name: "Burlington International Airport" },
        { code: "BUF", name: "Buffalo Niagara International" },
        { code: "BUR", name: "Bob Hope Airport" },
        { code: "BWI", name: "Baltimore-Washington International" },
        { code: "BZN", name: "Bozeman Yellowstone International" },
        { code: "CAE", name: "Columbia Metropolitan Airport" },
        { code: "CAK", name: "Akron-Canton Regional Airport" },
        { code: "CDC", name: "Cedar City Regional Airport" },
        { code: "CDV", name: "Merle K. Smith Airport" },
        { code: "CEC", name: "Del Norte County Airport" },
        { code: "CHA", name: "Chattanooga Metropolitan Airport" },
        { code: "CHO", name: "Charlottesville-Albemarle Airport" },
        { code: "CHS", name: "Charleston International Airport" },
        { code: "CID", name: "The Eastern Iowa Airport" },
        { code: "CIU", name: "Chippewa County International" },
        { code: "CLD", name: "McClellan-Palomar Airport" },
        { code: "CLE", name: "Cleveland Hopkins International" },
        { code: "CLL", name: "Easterwood Airport" },
        { code: "CLT", name: "Charlotte Douglas International" },
        { code: "CMH", name: "Port Columbus International" },
        { code: "CMI", name: "University of Illinois - Willard" },
        { code: "CMX", name: "Houghton County Memorial" },
        { code: "CNY", name: "Canyonlands Field" },
        { code: "COD", name: "Yellowstone Regional Airport" },
        { code: "COS", name: "City of Colorado Springs Municipal" },
        { code: "COU", name: "Columbia Regional Airport" },
        { code: "CPR", name: "Natrona County International" },
        { code: "CRP", name: "Corpus Christi International" },
        { code: "CRW", name: "Yeager Airport" },
        { code: "CSG", "name": "Columbus Metropolitan Airport" },
        { code: "CVG", name: "Cincinnati/Northern Kentucky Intl" },
        { code: "CWA", name: "Central Wisconsin Airport" },
        { code: "DAB", name: "Daytona Beach International" },
        { code: "DAL", name: "Dallas Love Field" },
        { code: "DAY", name: "James M. Cox Dayton International" },
        { code: "DBQ", name: "Dubuque Regional Airport" },
        { code: "DCA", name: "Ronald Reagan Washington National" },
        { code: "DEN", name: "Denver International Airport" },
        { code: "DFW", name: "Dallas/Fort Worth International" },
        { code: "DHN", name: "Dothan Regional Airport" },
        { code: "DIK", name: "Dickinson Theodore Roosevelt" },
        { code: "DLG", name: "Dillingham Airport" },
        { code: "DLH", name: "Duluth International Airport" },
        { code: "DRO", name: "Durango-La Plata County Airport" },
        { code: "DSM", name: "Des Moines International Airport" },
        { code: "DTW", name: "Detroit Metropolitan Airport" },
        { code: "DVL", name: "Devils Lake Regional Airport" },
        { code: "EAU", name: "Chippewa Valley Regional Airport" },
        { code: "ECP", name: "Northwest Florida Beaches Intl" },
        { code: "EGE", name: "Eagle County Regional Airport" },
        { code: "EKO", name: "Elko Regional Airport" },
        { code: "ELM", name: "Elmira/Corning Regional Airport" },
        { code: "ELP", name: "El Paso International Airport" },
        { code: "ERI", name: "Erie International Airport" },
        { code: "ESC", name: "Delta County Airport" },
        { code: "EUG", name: "Eugene Airport" },
        { code: "EVV", name: "Evansville Regional Airport" },
        { code: "EWN", name: "Coastal Carolina Regional Airport" },
        { code: "EWR", name: "Newark Liberty International" },
        { code: "EYW", name: "Key West International Airport" },
        { code: "FAI", name: "Fairbanks International Airport" },
        { code: "FAR", name: "Hector International Airport" },
        { code: "FAT", name: "Fresno Yosemite International" },
        { code: "FAY", name: "Fayetteville Regional Airport" },
        { code: "FCA", name: "Glacier Park International" },
        { code: "FLG", name: "Flagstaff Pulliam Airport" },
        { code: "FLL", name: "Fort Lauderdale-Hollywood Intl" },
        { code: "FNT", name: "Bishop International Airport" },
        { code: "FSD", name: "Sioux Falls Regional Airport" },
        { code: "FSM", name: "Fort Smith Regional Airport" },
        { code: "FWA", name: "Fort Wayne International Airport" },
        { code: "GCC", name: "Gillette-Campbell County Airport" },
        { code: "GCK", name: "Garden City Regional Airport" },
        { code: "GEG", name: "Spokane International Airport" },
        { code: "GFK", name: "Grand Forks International" },
        { code: "GGG", name: "East Texas Regional Airport" },
        { code: "GJT", name: "Grand Junction Regional Airport" },
        { code: "GNV", name: "Gainesville Regional Airport" },
        { code: "GPT", name: "Gulfport-Biloxi International" },
        { code: "GRB", name: "Green Bay-Austin Straubel Intl" },
        { code: "GRI", name: "Central Nebraska Regional Airport" },
        { code: "GRK", name: "Killeen-Fort Hood Regional" },
        { code: "GRR", name: "Gerald R. Ford International" },
        { code: "GSO", name: "Piedmont Triad International" },
        { code: "GSP", name: "Greenville-Spartanburg Intl" },
        { code: "GST", name: "Gustavus Airport" },
        { code: "GTF", name: "Great Falls International Airport" },
        { code: "GTR", name: "Golden Triangle Regional Airport" },
        { code: "GUC", name: "Gunnison-Crested Butte Regional" },
        { code: "GUM", name: "Guam International Airport" },
        { code: "HDN", name: "Yampa Valley Airport" },
        { code: "HIB", name: "Range Regional Airport" },
        { code: "HLN", name: "Helena Regional Airport" },
        { code: "HNL", name: "Honolulu International Airport" },
        { code: "HOB", name: "Lea County Regional Airport" },
        { code: "HOU", name: "William P. Hobby Airport" },
        { code: "HPN", name: "Westchester County Airport" },
        { code: "HRL", name: "Valley International Airport" },
        { code: "HSV", name: "Huntsville International Airport" },
        { code: "HYA", name: "Barnstable Municipal Airport" },
        { code: "HYS", name: "Hays Regional Airport" },
        { code: "IAD", name: "Washington Dulles International" },
        { code: "IAG", name: "Niagara Falls International" },
        { code: "IAH", name: "George Bush Intercontinental" },
        { code: "ICT", name: "Wichita Dwight D. Eisenhower National" },
        { code: "IDA", name: "Idaho Falls Regional Airport" },
        { code: "ILG", name: "Wilmington Airport" },
        { code: "ILM", name: "Wilmington International Airport" },
        { code: "IMT", name: "Ford Airport" },
        { code: "IND", name: "Indianapolis International Airport" },
        { code: "INL", name: "Falls International Airport" },
        { code: "ISN", name: "Sloulin Field International" },
        { code: "ISP", name: "Long Island MacArthur Airport" },
        { code: "ITH", name: "Ithaca Tompkins Regional Airport" },
        { code: "ITO", name: "Hilo International Airport" },
        { code: "JAC", name: "Jackson Hole Airport" },
        { code: "JAN", name: "Jackson-Evers International" },
        { code: "JAX", name: "Jacksonville International Airport" },
        { code: "JFK", name: "John F. Kennedy International" },
        { code: "JLN", name: "Joplin Regional Airport" },
        { code: "JMS", name: "Jamestown Regional Airport" },
        { code: "JNU", name: "Juneau International Airport" },
        { code: "KOA", name: "Kona International Airport" },
        { code: "KTN", name: "Ketchikan International Airport" },
        { code: "LAN", name: "Capital Region International" },
        { code: "LAR", name: "Laramie Regional Airport" },
        { code: "LAS", name: "McCarran International Airport" },
        { code: "LAW", name: "Lawton-Fort Sill Regional Airport" },
        { code: "LAX", name: "Los Angeles International Airport" },
        { code: "LBB", name: "Lubbock Preston Smith Intl" },
        { code: "LBE", name: "Arnold Palmer Regional Airport" },
        { code: "LCH", name: "Lake Charles Regional Airport" },
        { code: "LEX", name: "Blue Grass Airport" },
        { code: "LFT", name: "Lafayette Regional Airport" },
        { code: "LGA", name: "LaGuardia Airport" },
        { code: "LGB", name: "Long Beach Airport" },
        { code: "LIH", name: "Lihue Airport" },
        { code: "LIT", name: "Bill and Hillary Clinton National" },
        { code: "LNK", name: "Lincoln Airport" },
        { code: "LRD", name: "Laredo International Airport" },
        { code: "LSE", name: "La Crosse Regional Airport" },
        { code: "LWS", name: "Lewiston-Nez Perce County Airport" },
        { code: "MAF", name: "Midland International Airport" },
        { code: "MBS", name: "MBS International Airport" },
        { code: "MCI", name: "Kansas City International Airport" },
        { code: "MCO", name: "Orlando International Airport" },
        { code: "MDT", name: "Harrisburg International Airport" },
        { code: "MDW", name: "Chicago Midway International" },
        { code: "MEI", name: "Meridian Regional Airport" },
        { code: "MEM", name: "Memphis International Airport" },
        { code: "MFE", name: "McAllen-Miller International" },
        { code: "MFR", name: "Rogue Valley International" },
        { code: "MGM", name: "Montgomery Regional Airport" },
        { code: "MHK", name: "Manhattan Regional Airport" },
        { code: "MHT", name: "Manchester-Boston Regional" },
        { code: "MIA", name: "Miami International Airport" },
        { code: "MKE", name: "General Mitchell International" },
        { code: "MKG", name: "Muskegon County Airport" },
        { code: "MLB", name: "Melbourne International Airport" },
        { code: "MLI", name: "Quad City International Airport" },
        { code: "MLU", name: "Monroe Regional Airport" },
        { code: "MMH", name: "Mammoth Yosemite Airport" },
        { code: "MOB", name: "Mobile Regional Airport" },
        { code: "MOT", name: "Minot International Airport" },
        { code: "MQT", name: "Sawyer International Airport" },
        { code: "MRY", name: "Monterey Regional Airport" },
        { code: "MSN", name: "Dane County Regional Airport" },
        { code: "MSO", name: "Missoula International Airport" },
        { code: "MSP", name: "Minneapolis-Saint Paul Intl" },
        { code: "MSY", name: "Louis Armstrong New Orleans Intl" },
        { code: "MTJ", name: "Montrose Regional Airport" },
        { code: "MVY", name: "Martha's Vineyard Airport" },
        { code: "MYR", name: "Myrtle Beach International" },
        { code: "OAJ", name: "Albert J. Ellis Airport" },
        { code: "OAK", name: "Oakland International Airport" },
        { code: "OGG", name: "Kahului Airport" },
        { code: "OKC", name: "Will Rogers World Airport" },
        { code: "OMA", name: "Eppley Airfield" },
        { code: "OME", name: "Nome Airport" },
        { code: "ONT", name: "Ontario International Airport" },
        { code: "ORD", name: "Chicago O'Hare International" },
        { code: "ORF", name: "Norfolk International Airport" },
        { code: "ORH", name: "Worcester Regional Airport" },
        { code: "OTH", name: "Southwest Oregon Regional Airport" },
        { code: "OTZ", name: "Ralph Wien Memorial Airport" },
        { code: "PAH", name: "Barkley Regional Airport" },
        { code: "PBG", name: "Plattsburgh International Airport" },
        { code: "PBI", name: "Palm Beach International Airport" },
        { code: "PDX", name: "Portland International Airport" },
        { code: "PHF", name: "Newport News/Williamsburg Intl" },
        { code: "PHL", name: "Philadelphia International Airport" },
        { code: "PHX", name: "Phoenix Sky Harbor International" },
        { code: "PIA", name: "General Wayne A. Downing Peoria Intl" },
        { code: "PIB", name: "Hattiesburg-Laurel Regional Airport" },
        { code: "PIH", name: "Pocatello Regional Airport" },
        { code: "PIT", name: "Pittsburgh International Airport" },
        { code: "PLN", name: "Pellston Regional Airport" },
        { code: "PNS", name: "Pensacola International Airport" },
        { code: "PPG", name: "Pago Pago International Airport" },
        { code: "PSC", name: "Tri-Cities Airport" },
        { code: "PSE", name: "Mercedita Airport" },
        { code: "PSG", name: "Petersburg James A. Johnson" },
        { code: "PSP", name: "Palm Springs International Airport" },
        { code: "PUB", name: "Pueblo Memorial Airport" },
        { code: "PVD", name: "Theodore Francis Green State" },
        { code: "PWM", name: "Portland International Jetport" },
        { code: "RAP", name: "Rapid City Regional Airport" },
        { code: "RDD", name: "Redding Municipal Airport" },
        { code: "RDM", name: "Redmond Municipal Airport" },
        { code: "RDU", name: "Raleigh-Durham International Airport" },
        { code: "RHI", name: "Rhinelander-Oneida County Airport" },
        { code: "RIC", name: "Richmond International Airport" },
        { code: "RKS", name: "Rock Springs-Sweetwater County" },
        { code: "RNO", name: "Reno/Tahoe International Airport" },
        { code: "ROA", name: "Roanoke Regional Airport" },
        { code: "ROC", name: "Greater Rochester International" },
        { code: "ROW", name: "Roswell International Air Center" },
        { code: "RST", name: "Rochester International Airport" },
        { code: "RSW", name: "Southwest Florida International" },
        { code: "SAF", name: "Santa Fe Municipal Airport" },
        { code: "SAN", name: "San Diego International Airport" },
        { code: "SAT", name: "San Antonio International Airport" },
        { code: "SAV", name: "Savannah/Hilton Head Intl" },
        { code: "SBA", name: "Santa Barbara Municipal Airport" },
        { code: "SBN", name: "South Bend International Airport" },
        { code: "SBP", name: "San Luis Obispo County Regional" },
        { code: "SCC", name: "Deadhorse Airport" },
        { code: "SCE", name: "University Park Airport" },
        { code: "SDF", name: "Louisville International Airport" },
        { code: "SEA", name: "Seattle-Tacoma International" },
        { code: "SFO", name: "San Francisco International" },
        { code: "SGF", name: "Springfield-Branson National" },
        { code: "SGU", name: "St. George Regional Airport" },
        { code: "SHV", name: "Shreveport Regional Airport" },
        { code: "SIT", name: "Sitka Rocky Gutierrez Airport" },
        { code: "SJC", name: "Norman Y. Mineta San José Intl" },
        { code: "SJT", name: "San Angelo Regional Airport" },
        { code: "SJU", name: "Luis Muñoz Marín International" },
        { code: "SLC", name: "Salt Lake City International" },
        { code: "SMF", name: "Sacramento International Airport" },
        { code: "SMX", name: "Santa Maria Public Airport" },
        { code: "SNA", name: "John Wayne Airport" },
        { code: "SPI", name: "Abraham Lincoln Capital Airport" },
        { code: "SPS", name: "Wichita Falls Municipal Airport" },
        { code: "SRQ", name: "Sarasota-Bradenton International" },
        { code: "STC", name: "St. Cloud Regional Airport" },
        { code: "STL", name: "St. Louis International Airport" },
        { code: "STT", name: "Cyril E. King Airport" },
        { code: "STX", name: "Henry E. Rohlsen Airport" },
        { code: "SUN", name: "Friedman Memorial Airport" },
        { code: "SUX", name: "Sioux Gateway Airport" },
        { code: "SWF", name: "Stewart International Airport" },
        { code: "SYR", name: "Syracuse Hancock International" },
        { code: "TLH", name: "Tallahassee International Airport" },
        { code: "TOL", name: "Toledo Express Airport" },
        { code: "TPA", name: "Tampa International Airport" },
        { code: "TRI", name: "Tri-Cities Regional Airport" },
        { code: "TTN", name: "Trenton Mercer Airport" },
        { code: "TUL", name: "Tulsa International Airport" },
        { code: "TUS", name: "Tucson International Airport" },
        { code: "TVC", name: "Cherry Capital Airport" },
        { code: "TWF", name: "Magic Valley Regional Airport" },
        { code: "TXK", name: "Texarkana Regional Airport" },
        { code: "TYR", name: "Tyler Pounds Regional Airport" },
        { code: "TYS", name: "McGhee Tyson Airport" },
        { code: "VEL", name: "Valdez Airport" },
        { code: "VLD", name: "Valdosta Regional Airport" },
        { code: "VPS", name: "Destin-Fort Walton Beach Airport" },
        { code: "WRG", name: "Wrangell Airport" },
        { code: "WYS", name: "Westerly State Airport" },
        { code: "XNA", name: "Northwest Arkansas Regional" },
        { code: "YAK", name: "Yakutat Airport" },
        { code: "YUM", name: "Yuma International Airport" }
    ];

    const airportSelect = document.getElementById('originAirport');
    const airlineSelect = document.getElementById('airline');
    const predictBtn = document.getElementById('predictBtn');
    const notif = document.getElementById('notification');

    // Populate Airports
    airportData.forEach(item => {
        const option = document.createElement('option');
        option.value = item.code;
        option.textContent = `${item.code} - ${item.name}`;
        airportSelect.appendChild(option);
    });

    // Populate Airlines
    airlineData.forEach(item => {
        const option = document.createElement('option');
        option.value = item.code;
        option.textContent = item.name;
        airlineSelect.appendChild(option);
    });

    notif.textContent = "STATUS: ONLINE (336 LOCATIONS LOADED)";
    notif.style.color = "#00cc66";

    // Button Interaction
    predictBtn.addEventListener('click', () => {
        notif.textContent = "STATUS: CALCULATING...";
        notif.style.color = "#ff4d94";
        setTimeout(() => {
            notif.textContent = "STATUS: COMPLETE";
            notif.style.color = "#333";
        }, 1200);
    });
});